version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container_tpsymfony1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpsymfony1
      MYSQL_USER: tpsymfony1op
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container_tpsymfony1
    environment:
      PMA_HOST: mysql
      PMA_USER: tpsymfony1op
      PMA_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
    driver: bridge
